server.port=${SERVER_PORT:8081}
spring.application.name=Generator

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=${GEMINI_CHAT_MODEL:gemini-3.1-flash-lite}

spring.app.jwtSecretKey=${JWT_SECRET_KEY}
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.app.frontend-url=${FRONTEND_URL:https://makeshift-blond.vercel.app}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

deepgram.api.key=${DEEPGRAM_API_KEY}
